name: "Dev Deployment"

on:
  push:
    branches:
      - main
    paths:
      - "!**/readme.md"
      - "variables/Dev/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_dev_resources:
    name: development_env
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/01_terraform_encode.yml
    with:
      environment: "dv"
      environment_instance: "01"
      state_file_prefix: "development_state"
      environment_name: "SUBSCRIPTION-DEVELOPMENT-01"
      pipeline_agent: "ubuntu-latest"
      variable_file_path: "variables/Dev"
      backend_file_directory: "variables/"
      working_directory: "variables"
    secrets:
      client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      subscription_id: ${{ secrets.SUBSCRIPTION-DEVELOPMENT-01 }}
